<?php

namespace app\controllers;

use Yii;
use yii\helpers\ArrayHelper;

class LanguageController
{
    private static $translations = [
        'es-ES' => [
            'Home' => 'Inicio',
            'About' => 'Acerca de',
            'Contact' => 'Contacto',
            'Language' => 'Idioma',
            'Courses' => 'Cursos',
            'By category' => 'Por categoría',
            'All' => 'Todos',
            'My account' => 'Mi cuenta',
            'My profile' => 'Mi perfil',
            'Change password' => 'Cambiar contraseña',
            'Logout' => 'Cerrar sesión',
            'Search' => 'Buscar',
            'Reset' => 'Restablecer',
            'Categories' => 'Categorías',
            'Category' => 'Categoría',
            'Latest Products' => 'Últimos productos',
            'Uploaded files for this course' => 'Ficheros del curso',
            'There are no uploaded files for this course' => 'No existen ficheros disponibles para este curso',
            'This is the About page. You may modify the following file to customize its content:' => 'Ésta es la página de información general. Modifique su contenido en:',
            'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Si tiene alguna inquietud o duda, utilice el siguiente formulario para contactarnos. Gracias.',
            'Submit' => 'Enviar',
            'The above error occurred while the Web server was processing your request.' => 'Este error ocurrió al procesar su solicitud.',
            'Please contact us if you think this is a server error. Thank you.' => 'Por favor, contáctenos si piensa que se trata de un error de la aplicación. Gracias.',
            'Login' => 'Acceder',
            'Please fill out the following fields to login:' => 'Por favor, introduzca sus datos para continuar',
            'If you forgot your password, you can' => 'Si ha olvidado su contraseña, puede ',
            'reset it here' => 'restablecerla aquí',
            'Request password reset' => 'Restablecer contraseña',
            'Please fill out your email. A link to reset password will be sent there.' => 'Introduzca su dirección de correo y recibirá instrucciones para restablecer su contraseña.',
            'Please choose your new password:' => 'Por favor, escoja una nueva contraseña',
            'Signup' => 'Registro',
            'Please fill out the following form to signup:' => 'Complete el siguiente formulario para registrarse en el sitio',
            'Verification code' => 'Código de verificación',
            'Name' => 'Nombre',
            'Subject' => 'Asunto',
            'Body' => 'Contenido',
            'Username' => 'Usuario',
            'Password' => 'Contraseña',
            'Email' => 'Correo electrónico',
            'Status' => 'Estado',
            'Role' => 'Rol',
            'Surname' => 'Apellidos',
            'Identification document' => 'Documento de identidad',
            'Identification number' => 'Número de identidad',
            'Mobile phone' => 'Celular',
            'Telephone' => 'Teléfono fijo',
            'Address' => 'Dirección',
            'PO Box' => 'Código postal',
            'Municipality' => 'Municipio',
            'Province' => 'Provincia',
            'Country' => 'País',
            'Referred by' => 'Referido por',
            'I agree with terms and conditions.' => 'Acepto los términos y condiciones de uso.',
            'Access level' => 'Nivel de acceso',
            'Created at' => 'Creado el',
            'Modified at' => 'Modificado el',
            'Failed logon attempts' => 'Intentos de conexión fallidos',
            'Authorization Key' => 'Clave de acceso',
            'Password Reset Token' => 'Código de restablecimiento de contraseña',
            'Update my profile' => 'Actualizar mi perfil',
            'Users' => 'Usuarios',
            'Update profile' => 'Actualizar perfil',
            'Personal information' => 'Mis datos',
            'Accept' => 'Aceptar',
            'Update' => 'Actualizar',
            'Change password' => 'Cambiar contraseña',
            'Reset password' => 'Restablecer contraseña',
            'My profile' => 'Mi perfil',
            'Users' => 'Usuarios',
            'You are not allowed to perform this action.' => 'No está autorizado a ejecutar la acción solicitada.',
            'Welcome to PonderNet!' => '¡Bienvenido a PonderNet!',
            'A new Online Education Website' => 'Una nueva Web de Formación Online',
            'Available courses' => 'Cursos disponibles',
            'My affiliate link: ' => 'Mi link de afiliado: ',
            'There is no user with such access key.' => 'La clave de acceso no existe.',
            'You must specify your verification token' => 'Debe especificar un código de verificación correcto',
            'Incorrect verification token.' => 'Código de verificación incorrecto.',
            'Authorization key' => 'Código de autorización',
            'Belongs to' => 'Pertenece a',
            'Description' => 'Descripción',
            'Current password' => 'Contraseña actual',
            'New password' => 'Contraseña nueva',
            'Confirm new password' => 'Confirmar contraseña',
            'Invitation type' => 'Tipo de invitación',
            'Invited by' => 'Invitado por',
            'Course' => 'Curso',
            'Remember me' => 'Recordar mis datos',
            'There is no user with such email.' => 'No existe ningún usuario registrado con ese correo.',
            'Password reset for ' => 'Restablecer contraseña de ',
            'Maximum allowed filesize is ' => 'El tamaño máximo permitido es ',
            'Minimum allowed filesize is ' => 'El tamaño mínimo permitido es ',
            'File extension is not allowed ' => 'El archivo no contiene una extensión permitida ',
            'Maximum file count is ' => 'El máximo de archivos permitidos es ',
            'This field is mandatory' => 'Este dato es obligatorio',
            'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrecto.',
            'This field has an incorrect format' => 'Este dato no tiene el formato correcto',
            'This element does not exist' => 'Este elemento no existe',
            'Course to buy' => 'Curso a comprar',
            'Account activation for user ' => 'Confirmar registro de ',
            'You have already bought this course.' => 'Usted ya ha abonado la cuota de este curso.',
            'Payment process has not been completed. Try again later.' => 'El proceso de pago no se ha completado. Inténtenlo nuevamente.',
            'Unable to download this file.' => 'No se puede descargar este fichero.',
            'You must select a valid filename.' => 'Debe seleccionar un nombre de archivo válido.',
            'You haven\'t paid yet for this course.' => 'Usted no ha abonado aun la cuota correspondiente a este curso.',
            'Your user account has been blocked for security reasons. Contact the site administrator to unlock it.' => 'Su cuenta ha sido bloqueada por razones de seguridad. Contacte al administrador del sistema para desbloquearla.',
            'Thank you for contacting us. We will reply as soon as possible.' => 'Gracias por ponerse en contacto. Le responderemos a la mayor brevedad posible.',
            'There was an error sending email.' => 'Ocurrió un error al enviar el correo.',
            'Invalid request.' => 'Petición incorrecta',
            'An email has been sent to your address with further instructions.' => 'Le hemos enviado un correo electrónico con instrucciones para continuar el proceso.',
            'Sorry, we are unable to send the instructions to your email address.' => 'Lo sentimos, pero ha sido imposible enviarle las instrucciones a su cuenta de correo.',
            'One or more values are violating database restrictions.' => 'Al menos uno de los datos introducidos violan las restricciones de la base de datos.',
            'An error has occured with code ' => 'Ha ocurrido un error con el código ',
            'Your password has been updated.' => 'Su contraseña ha sido actualizada.',
            'Your account has been activated. Now you may logon to continue.' => 'Su cuenta ha sido activada. Inicie sesión para continuar',
            'Your account has not been activated.' => 'Su cuenta de usuario no ha podido ser activada',
            'Unable to save data.' => 'No se han podido guardar los datos',
            'Current password is incorrect.' => 'La contraseña actual no coincide.',
            'Cannot send an invitation to an existing user.' => 'No puede invitar a un usuario registrado.',
            'Invitation for' => 'Invitación a ',
            'The message has been sent.' => 'El mensaje ha sido enviado.',
            'An error occured while attempting to retire your funds. Please, try again.' => 'Ha ocurrido un error al intentar retirar sus fondos. Por favor, inténtelo nuevamente.',
            'You are not allowed to retire your funds yet.' => 'Usted no puede retirar sus fondos aun',
            'Thanks for staying with us! Your account has been reinserted into the circuit.' => '¡Gracias por continuar con nosotros! Su cuenta ha sido reinsertada en el circuito.',
            'Thanks for your support. Your account has been removed from our system.' => 'Gracias por su apoyo. Su cuenta de usuario ya no se encuentra activa en el sistema.',
            'Buy' => 'Comprar',
            'Buy course' => 'Comprar curso',
            'Process completed' => 'Proceso completado',
            'Thanks for buying this course!' => '¡Gracias por comprar este curso!',
            'Now you can download its files from ' => 'Ahora puede acceder a sus ficheros desde ',
            'this link' => 'este enlace',
            'There are no files for this course yet.' => 'No existen ficheros disponibles aun para este curso.',
            'The main directory for this course does not exist.' => 'No existe el directorio raíz del curso.',
            'About this site.' => 'Acerca de este sitio.',
            'Active' => 'Activo',
            'Inactive' => 'Inactivo',
            'Blocked' => 'Bloqueado',
            'Visit our full products catalogue' => 'Visitar el catálogo de productos',
            'Office' => 'Oficina',
            'My Office' => 'Mi Oficina',
            'Affiliate link: ' => 'Link de afiliado: ',
            'Sending invitations' => 'Enviar invitaciones',
            'Join our site' => 'Registrarse en el sitio',
            'Buy a course' => 'Comprar un curso',
            'My sold courses' => 'Mis ventas',
            'Buyer' => 'Comprador',
            'Income' => 'Ganancia',
            'Total amount: ' => 'Total: ',
            'Retire funds' => 'Retirar fondos',
            'Are you sure you want to retire your uncollected funds?' => '¿Confirma que desea retirar sus fondos acumulados?',
            'My current credit: ' => 'Mi crédito actual: ',
            'You must select a course' => 'Debe seleccionar un curso',
            'Hello' => 'Hola',
            'Follow the link below to activate your user account:' => 'Utilice el vínculo a continuación para activar su cuenta de usuario:',
            'Follow the link below to reset your password:' => 'Utilice el vínculo a continuación para restablecer su contraseña:',
            'Please, follow the link below to visit your office:' => 'Utilice el vínculo a continuación para acceder a su oficina:',
            'You have just gained access to retire your funds on ' => 'Ya puede pasar por su oficina y retirar los fondos acumulados en ',
            'Dear user:' => 'Estimado usuario:',
            'has sent you an invitation to ' => 'le ha invitado a ',
            'buy the course ' => 'comprar el curso ',
            'join him' => 'registrarse',
            ' on ' => ' en ',
            'Please, follow the link below to accept it:' => 'Por favor, utilice el siguiente vínculo para aceptar la invitación:',
            'Do you wish to stay on the continuous training plan and generate another 3000€?' => '¿Desea continuar con el plan de formación continua y generar otros 3000€?',
            'Yes' => 'Sí',
            'No' => 'No',
            'Continue' => 'Continuar',
            'Cancel' => 'Cancelar',
            'When retiring funds, you must specify whether you want to stay in the system or not.' => 'Al retirar fondos, debe especificar si desea continuar o no en el sistema.',
            'New password does not match' => 'La nueva contraseña no coincide',
            'You must accept terms and conditions to continue' => 'Debe aceptar los términos y condiciones de uso para continuar',
            'Another user has already registered with this information' => 'Ya existe un usuario registrado con este dato',
            'Since you have bought your first course, your account is already active.' => 'Su cuenta ya se encuentra activa gracias a la compra de su primer curso.',
            'Thanks for joining us!' => '¡Gracias por unirse al equipo!',
            'Quick Start Bonus' => 'Cobrar Bono de Inicio Rápido',
            'Confirm payment' => 'Confirmar pago',
            'Details' => 'Detalles',
            'View all...' => 'Ver todas...',
            ' by ' => ' por ',
            'Retire Quick Start Bonus' => 'Cobrar Bono de Inicio Rápido',
            'Operations' => 'Operaciones',
            'Operation completed.' => 'Operación completada',
            'Stay in PonderNET' => 'Continuar en PonderNET',
            'Do you wish to retire this guick start bonus?' => '¿Desea retirar este bono de inicio rápido?',
            'My quick start bonuses: ' => 'Mis bonos de inicio rápido: ',
            'My boxes' => 'Mis cajas',
            'Box ' => 'Caja ',
            'User details for ' => 'Datos del usuario ',
            'Are you sure you want to continue?' => '¿Seguro que desea continuar?',
            'My bought courses' => 'Mis compras',
            'My wallet' => 'Mi billetera',
            'Credit' => 'Importe',
            'Type' => 'Tipo',
            'Payed by' => 'Pagado por',
            'Request date' => 'Solicitado el',
            'Payment date' => 'Pagado el',
            'Pending' => 'Por cobrar',
            'Payed' => 'Pagado',
            'Financial history' => 'Historial financiero',
            'User' => 'Usuario',
            'My payments' => 'Mis pagos',
            'Your password has been changed.' => 'Su contraseña ha sido actualizada',
            'Invitation for ' => 'Invitación a ',
            'You have succesfully created an user account on' => 'Se ha creado una cuenta de usuario con su dirección de correo en',
            'You may also ' => 'También puede ',
            'register for free' => 'registrarse de manera gratuita',
            'Invitation link: ' => 'Link para invitar: ',
            'Manage site' => 'Administrar sitio',
            'Your profile has been updated' => 'Su perfil ha sido actualizado',
            'with the following information: ' => 'con los datos siguientes: ',
            'Confirm registration' => 'Confirmar registro',
            'PonderNET is an online community focused on education. It\'s a buy & sell platform with different educative resources: a complete set of digital tools and products to get people closer to success.' =>
            'PonderNET es una comunidad online destinada a la formación no reglada. Se trata de una plataforma de compra-venta de diferentes cursos formativos: toda una serie de herramientas y productos digitales que buscan acercar a las personas al éxito.',
            'While the user gets educated, he has the opportunity of joining our system and becoming a part of an online business full of opportunities, that allows him to increase his income and personal life. And everything comes through knowledge!' =>
            'Al mismo tiempo que el usuario se forma, tiene la posibilidad de afiliarse a nuestro sistema y formar parte de un negocio online lleno de oportunidades, que le permite mejorar su economía y su vida personal, ¡y todo a través del conocimiento!',
            'PonderNET looks for a balance in people\'s lives through an updated educational offer, making a good use of the latest technological tools. PonderNET is the seed of a worldwide family which most valuable asset is learning, which makes it possible to obtain economical prosperity.' =>
            'Ponder Net busca un equilibrio en la vida de las personas mediante una oferta formativa actualizada, haciendo uso de las últimas herramientas tecnológicas. Ponder Net es la semilla de una familia mundial cuyo mejor valor es el aprendizaje y, a través de éste, es posible llegar a la prosperidad económica.',
            'Join us!' => '¡Súmate a nosotros!',
            
        ],
        'fr-FR' => [
            'About' => 'À propos de',
            'Contact' => 'Contact',
            'Language' => 'Langue',
            'Courses' => 'Cours',
            'By category' => 'Pour catégorie',
            'All' => 'Tous',
            'My account' => 'Mon rôle',
            'My profile' => 'Mon profil',
            'Change password' => 'Changer contremarque',
            'Logout' => 'Partir',
            'Search' => 'Chercher',
            'Reset' => 'Restaurer',
            'Categories' => 'Catégories',
            'Category' => 'Catégorie',
            'Latest Products' => 'Dernier produits',
            'Office' => 'Bureau',
            'A new Online Education Website' => 'Une nouvelle page de formation digital',
            'PonderNET is an online community focused on education. It\'s a buy & sell platform with different educative resources: a complete set of digital tools and products to get people closer to success.' =>
            'Ponder Net est une communauté online destinée à la formation. Elle est une plateforme pour l\'achat et la vente de différents cours de formation: une gamme d\'outils et produits digitaux qui approchent aux gents à obtenir le succès.',
            'While the user gets educated, he has the opportunity of joining our system and becoming a part of an online business full of opportunities, that allows him to increase his income and personal life. And everything comes through knowledge!' =>
            'Alors que la personne se forme, elle a la possibilité de se joindre à notre système et faire partie d\'un affaire online plein d\'oportunités, qui lui permet d\'améliorer son économie et sa vie personnelle, et tout à travers la connaissance!',
            'PonderNET looks for a balance in people\'s lives through an updated educational offer, making a good use of the latest technological tools. PonderNET is the seed of a worldwide family which most valuable asset is learning, which makes it possible to obtain economical prosperity.' =>
            'Ponder Net cherche un équilibre dans la vie des gens à travers d’une offert de formation actualisé, en utilisant les derniers outils technologiques. Ponder Net est la graine d\'une famille mondiale dans la quelle son meilleur valeur est l\'aprentissage et, à travers de celle ci, il est possible d\'arriver à la prospérité économique.',
            'Join us!' => 'Rejoignez-nous!',
        ],
        'pt-PT' => [
            'Language' => 'Língua',
            'A new Online Education Website' => 'O nuovo sitio pra o formaçao digital',
            
        ],
    ];

    public static function translate($message)
    {
        $pp = Yii::$app->session;
        
        if (Yii::$app->session->has('language'))
        {
            $language = Yii::$app->session->get('language');
        }
        else
        {
            $language = Yii::$app->language;
        }
        $pp = $language;
        if ($language == 'en-US')
            return $message;
        if (ArrayHelper::keyExists($message, self::$translations[$language]))
            return self::$translations[$language][$message];
        return $message;
    }
}
